---
- name: ping
  hosts: all
  handlers:
    - name: 'recompile xmonad'
      become: false
      shell: 'xmonad --recompile'

  tasks:
    - name: Create base .profile
      copy:
        src: 'files/bash/profile'
        dest: '/home/{{ main_username }}/.profile'
        owner: '{{ main_username }}'
        group: '{{ main_username }}'

    - name: Create base .bashrc
      copy:
        src: 'files/bash/bashrc'
        dest: '/home/{{ main_username }}/.bashrc'
        owner: '{{ main_username }}'
        group: '{{ main_username }}'

    - name: Set bash aliases
      lineinfile:
        path: '/home/{{ main_username }}/.bash_aliases'
        search_string: 'alias {{ item.key }}'
        line: "alias {{ item.key }}='{{ item.value }}'"
        create: yes
        owner: '{{ main_username }}'
        group: '{{ main_username }}'
      loop: '{{ alias_definitions | dict2items }}'
      vars:
        alias_definitions:
          ni: 'npm install'
          nr: 'npm run'
          yr: 'yarn run'
          tf: 'terraform'
          tg: 'terragrunt'

    - name: Set global gitconfig
      community.general.git_config:
        scope: 'global'
        name: '{{ item.name }}'
        value: '{{ item.value }}'
      loop:
        - name: 'user.name'
          value: 'Miika Hänninen'
        - name: 'user.email'
          value: 'miika.hanninen@reaktor.com'
        - name: 'core.excludesfile'
          value: '~/.gitignore_global'
        - name: 'core.editor'
          value: 'vim'
        - name: 'push.default'
          value: 'simple'
        - name: 'alias.statsu'
          value: 'status'
        - name: 'alias.stauts'
          value: 'status'
        - name: 'alias.ll'
          value: "!exec git log --pretty='format: %C(auto) %h %G?%d %s' --abbrev-commit --graph --decorate --all --color | less -R -p 'HEAD'"
        - name: 'alias.fp'
          value: 'push --force-with-lease'
        - name: 'alias.fixup'
          value: 'commit --amend --no-edit'
        - name: 'alias.git'
          value: '!exec git'
        - name: 'diff.submodule'
          value: 'log'
        - name: 'commit.verbose'
          value: 'true'
        - name: 'merge.conflictstyle'
          value: 'diff3'
        - name: 'fetch.recurseSubmodules'
          value: 'on-demand'
        - name: 'status.submoduleSummary'
          value: 'true'
        - name: 'rebase.autosquash'
          value: 'true'
        - name: 'pull.ff'
          value: 'only'

    - name: Copy global gitignore
      copy:
        src: 'files/git/gitignore_global'
        dest: '/home/{{ main_username }}/.gitignore_global'
        owner: '{{ main_username }}'
        group: '{{ main_username }}'

    - name: Create vim config dir structure
      file:
        state: directory
        path: '/home/{{ main_username }}/{{ item }}'
        owner: '{{ main_username }}'
        group: '{{ main_username }}'
      loop:
        - '.vim'
        - '.vim/pack/'
        - '.vim/pack/ansible_managed'
        - '.vim/pack/ansible_managed/start'
        - '.vim/pack/ansible_managed/opt'

    - name: Copy vimrc
      copy:
        src: 'files/vim/vimrc'
        dest: '/home/{{ main_username }}/.vim/vimrc'
        owner: '{{ main_username }}'
        group: '{{ main_username }}'

    - name: Install vim plugins
      git:
        repo: '{{ item.repo }}'
        dest: '/home/{{ main_username }}/.vim/pack/ansible_managed/start/{{ item.name }}'
        version: '{{ item.version }}'
      loop:
        - name: 'ale'
          version: '19437e25d05950ab83dce285b4b8ec5166e06dba'
          repo: 'https://github.com/w0rp/ale.git'
        - name: 'bclose.vim'
          version: '99018b4a2dd18aea1cbd3aa23565b01a0f8c5b73'
          repo: 'https://github.com/rbgrouleff/bclose.vim.git'
        - name: 'ctrlp.vim'
          version: 'f68f4d00b9c99d0d711bfde3b071f0dafd249901'
          repo: 'https://github.com/ctrlpvim/ctrlp.vim.git'
        - name: 'editorconfig-vim'
          version: '3078cd10b28904e57d878c0d0dab42aa0a9fdc89'
          repo: 'https://github.com/editorconfig/editorconfig-vim.git'
        - name: 'elm-vim'
          version: '4b71facd77297cb33bbb3b14894676cff0a9bd1d'
          repo: 'https://github.com/ElmCast/elm-vim.git'
        - name: 'html5.vim'
          version: '7c9f6f38ce4f9d35db7eeedb764035b6b63922c6'
          repo: 'https://github.com/othree/html5.vim.git'
        - name: 'psc-ide-vim'
          version: '20ff325813ab114d70573a6768565a36aba796b9'
          repo: 'https://github.com/FrigoEU/psc-ide-vim.git'
        - name: 'purescript-vim'
          version: '5b4fa3e2970be1353f7d77735c0c9b42dc9885f3'
          repo: 'https://github.com/purescript-contrib/purescript-vim.git'
        - name: 'rust.vim'
          version: 'c06a17151c69b9d61e60a28274932a28fd37c453'
          repo: 'https://github.com/rust-lang/rust.vim.git'
        - name: 'tsuquyomi'
          version: '144526df5340d3bd0b413e6127c0393de171889a'
          repo: 'https://github.com/Quramy/tsuquyomi.git'
        - name: 'typescript-vim'
          version: '67e81e4292186889a1a519e1bf3a600d671237eb'
          repo: 'https://github.com/leafgarland/typescript-vim.git'
        - name: 'vim-base64'
          version: 'd15253105f6a329cd0632bf9dcbf2591fb5944b8'
          repo: 'https://github.com/christianrondeau/vim-base64.git'
        - name: 'vim-colors-solarized'
          version: '528a59f26d12278698bb946f8fb82a63711eec21'
          repo: 'https://github.com/altercation/vim-colors-solarized.git'
        - name: 'vim-commentary'
          version: '349340debb34f6302931f0eb7139b2c11dfdf427'
          repo: 'https://github.com/tpope/vim-commentary.git'
        - name: 'vim-dadbod'
          version: '6f8b99868fd5560d6eb47f82ca76ec62e3d5ae78'
          repo: 'https://github.com/tpope/vim-dadbod.git'
        - name: 'vim-elixir'
          version: '7e7f42cf10ba05b6d783de411a6ceca50fe0cc69'
          repo: 'https://github.com/elixir-editors/vim-elixir.git'
        - name: 'vim-eunuch'
          version: 'e8b1be581b88de524fc62cd24265d602f8caac19'
          repo: 'https://github.com/tpope/vim-eunuch.git'
        - name: 'vim-fugitive'
          version: 'e2927fb4676b499931a3c27a2dc8a8a8bc52ab55'
          repo: 'https://github.com/tpope/vim-fugitive.git'
        - name: 'vim-go'
          version: '4a429a0fc85c2a95b24544373516fdee805c3a56'
          repo: 'https://github.com/fatih/vim-go.git'
        - name: 'vim-heroku'
          version: 'a82bc493249c62a1fcd113a3c3ae6ff6931b72b5'
          repo: 'https://github.com/tpope/vim-heroku.git'
        - name: 'vim-javascript'
          version: 'f8345cdb6734aefa5c0f9cb128c9efd005410a43'
          repo: 'https://github.com/pangloss/vim-javascript.git'
        - name: 'vim-jsx'
          version: '8879e0d9c5ba0e04ecbede1c89f63b7a0efa24af'
          repo: 'https://github.com/mxw/vim-jsx.git'
        - name: 'vim-rhubarb'
          version: '82e71b150d28b60fa96a0e4fe3c84df691a9206a'
          repo: 'https://github.com/tpope/vim-rhubarb.git'
        - name: 'vim-surround'
          version: 'f51a26d3710629d031806305b6c8727189cd1935'
          repo: 'https://github.com/tpope/vim-surround.git'
        - name: 'vim-terraform'
          version: 'f0b17ac9f1bbdf3a29dba8b17ab429b1eed5d443'
          repo: 'https://github.com/hashivim/vim-terraform.git'
        - name: 'vim-toml'
          version: 'a4ec206052aa347d7df90dc4b6697b7f2b7929bc'
          repo: 'https://github.com/cespare/vim-toml.git'
        - name: 'vim-unimpaired'
          version: '825a3ee6407575dcaa24e756d6d71e4245615d1c'
          repo: 'https://github.com/tpope/vim-unimpaired.git'
        - name: 'vim-vinegar'
          version: '43576e84d3034bccb1216f39f51ed36d945d7b96'
          repo: 'https://github.com/tpope/vim-vinegar.git'

    - name: Create xmonad config dir
      file:
        state: directory
        path: '/home/{{ main_username }}/.xmonad'
        owner: '{{ main_username }}'
        group: '{{ main_username }}'

    - name: Copy xmonad config
      copy:
        src: 'files/xmonad/xmonad.hs'
        dest: '/home/{{ main_username }}/.xmonad/xmonad.hs'
        owner: '{{ main_username }}'
        group: '{{ main_username }}'
      notify:
        - 'recompile xmonad'

    - name: Copy xmobar config
      copy:
        src: 'files/xmobar/xmobarrc'
        dest: '/home/{{ main_username }}/.xmobarrc'
        owner: '{{ main_username }}'
        group: '{{ main_username }}'
