#!/bin/bash

set -euo pipefail

main() {
    local -r gh_user="${1:-}"
    local -r gh_repo="${2:-}"
    local -r initial_main_branch="${3:-}"

    if [ -z "$gh_user" ]; then
        echo "First param needs to be github username"
        exit 1
    fi

    if [ -z "$gh_repo" ]; then
        echo "Second param needs to be github repo name"
        exit 1
    fi

    local -r plugin_name="$gh_repo"
    local -r plugin_path=".vim/pack/googol/start/$plugin_name"

    git submodule add --force "https://github.com/$gh_user/$gh_repo.git" "$plugin_path"

    if [ -n "$initial_main_branch" ]; then
        pushd "$plugin_path"
        git checkout "$initial_main_branch"
        popd
    fi

    pushd "$plugin_path"
    local -r plugin_branch="$(git branch --show-current)"
    popd

    if [ "$plugin_branch" != "master" ]; then
        local -r repo_root="$(git rev-parse --show-toplevel)"
        local -r plugin_master_override_file="$repo_root/helperscripts/.master_overrides/$plugin_name"

        echo "$plugin_branch" > "$plugin_master_override_file"
        git add "$plugin_master_override_file"
    fi
}

main "$@"
