#!/bin/bash

set -euo pipefail

for plugin in .vim/pack/googol/start/*
do
    git -C "$plugin" fetch -q origin master &
done

wait 

for plugin in .vim/pack/googol/start/*
do
    echo
    basename "$plugin"
    git -C "$plugin" --no-pager log --oneline HEAD..origin/master
done

for plugin in .vim/pack/googol/start/*
do
    plugin_name="$(basename "$plugin")"
    short_stats="$(git -C "$plugin" --no-pager diff --shortstat HEAD..origin/master)"
    if [ -z "$short_stats" ]; then
        short_stats=" no updates"
    fi
    echo "${plugin_name}:${short_stats}"
done
