#!/bin/bash

set -euo pipefail


main() {
    local -r plugin_name=${1:-}
    local -r plugin_path=".vim/pack/googol/start/$plugin_name"

    if [ -z "$plugin_name" -o ! -d "$plugin_path" ]; then
        echo "First param needs to be the name of an already installed plugin"
        exit 1
    fi

    git submodule deinit "$plugin_path"
    git rm "$plugin_path"
    rm -rf ".git/modules/$plugin_path"
}

main "$@"
