#!/bin/bash

set -euo pipefail

PLUGIN_NAME=${1:-}

PLUGIN_PATH=".vim/pack/googol/start/$PLUGIN_NAME"

if [ -z "$PLUGIN_NAME" -o ! -d "$PLUGIN_PATH" ]; then
    echo "First param needs to be the name of an already installed plugin"
    exit 1
fi

git submodule deinit "$PLUGIN_PATH"
git rm "$PLUGIN_PATH"
rm -rf ".git/modules/$PLUGIN_PATH"
