#!/bin/bash

set -euo pipefail

PLUGIN_NAME=${1:-}

PLUGIN_PATH=".vim/pack/googol/start/$PLUGIN_NAME"

if [ -z "$PLUGIN_NAME" -o ! -d "$PLUGIN_PATH" ]; then
    echo "First param needs to be the name of an already installed plugin"
    exit 1
fi

cd "$PLUGIN_PATH"

git fetch -q origin master
git checkout -q origin/master
