#!/bin/bash

set -euo pipefail

main() {
    local -r plugin_name="${1:-}"
    local -r plugin_path=".vim/pack/googol/start/$plugin_name"
    local -r plugin_main_branch="$(get_upstream_main_branch "$plugin_name")"

    if [ -z "$plugin_name" -o ! -d "$plugin_path" ]; then
        echo "First param needs to be the name of an already installed plugin"
        exit 1
    fi

    cd "$plugin_path"

    git fetch -q origin "$plugin_main_branch"
    git checkout -q "origin/$plugin_main_branch"
}

get_upstream_main_branch() {
    local -r plugin_name="$1"
    local -r repo_root="$(git rev-parse --show-toplevel)"
    local -r plugin_master_override_file="$repo_root/helperscripts/.master_overrides/$plugin_name"


    if [ -f "$plugin_master_override_file" ]; then
        cat "$plugin_master_override_file"
    else
        echo "master"
    fi
}

main "$@"
