directory: /media/music/music
library: /media/music/beets/library.blb
asciify_paths: no
art_filename: cover
per_disc_numbering: yes
va_name: Various Artists

import:
    copy: yes
    write: yes
    move: no
    log: /media/music/beets/import.log
    timid: yes
    detail: yes

ui:
    color: yes

paths:
    default: $albumartist/$album%aunique{}/$disc-$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$disc-$track $artist $title

plugins: fetchart embedart ftintitle replaygain web
fetchart:
    auto: yes
embedart:
    auto: yes
ftintitle:
    auto: yes
replaygain:
    backend: gstreamer
web:
    host: 0.0.0.0
