input "*" {
  xkb_layout  "fi"
  xkb_variant "nodeadkeys"
  xkb_model   "pc101"
  xkb_options ""
}

input "1:1:AT_Translated_Set_2_keyboard" {
  xkb_layout  "fi"
  xkb_variant "nodeadkeys"
  xkb_model   "pc101"
  xkb_options ""
}

input "SYNA8018:00 06CB:CE67 Touchpad" {
  middle_emulation disabled
}
